name:                spread-feed
version:             0.1.0.0
github:              "rbnfrhnr/spread-feed"
license:             BSD3
author:              "Robin"
maintainer:          "frehner.robin@gmail.com"
copyright:           "2020 Robin Frehner"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rbnfrhnr/spread-feed#readme>

dependencies:
  - aeson  >=1.4.4.0
  - base >= 4.7 && < 5
  - bytestring ==0.10.8.2
  - configurator >=0.3.0.0
  - filepath >=1.4.2.1
  - milena >=0.5.4.0
  - utils >=0.1.0.0

library:
  source-dirs: src

executables:
  spread-feed-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spread-feed

tests:
  spread-feed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spread-feed
