name:                utils
version:             0.1.0.0
github:              "githubuser/utils"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/utils#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring ==0.10.8.2
  - bytestring-show >=0.3.5.6
  - connection ==0.3.1
  - configurator >=0.3.0.0
  - containers >=0.6.0.1
  - directory >=1.3.3.0
  - filepath >=1.4.2.1
  - influxdb >=1.7.1.1
  - lens >=4.17.1
  - milena >=0.5.4.0
  - network >=2.8.0.1
  - text >=1.2.3.1
  - time >=1.8.0.2
  - transformers >=0.5.6.2
  - websockets >=0.12.7.1
  - wuss >=1.1.16

library:
  source-dirs: src

executables:
  utils-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - utils

tests:
  utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - utils
